Repository jdneo/vscode-checkstyle, pull requests merged in 2021-01, with the labels that each got.

#288 doc: Add contribution page
  CONTRIBUTING.md
  jdtls.ext/com.shengchen.checkstyle.runner/target.target
Labels: engineering

#292 Fix the error column that’s reported to VS Code
  jdtls.ext/com.shengchen.checkstyle.checker/src/main/java/com/shengchen/checkstyle/checker/CheckerListener.java
Labels: bug

#297 refactor: Use protocolConverter to parse the workspace edit
  package-lock.json
  package.json
  src/utils/editUtils.ts
Labels: engineering

#290 Add multiple variable declarations quick fix
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/BaseQuickFix.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/FixableCheck.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/QuickFixService.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/coding/MultipleVariableDeclarationsQuickFix.java
  src/constants/quickFix.ts
Labels: enhancement

#294 Add quick fix all
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/BaseQuickFix.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/QuickFixService.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/coding/MultipleVariableDeclarationsQuickFix.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/DelegateCommandHandler.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/api/IQuickFixService.java
  src/checkstyleDiagnosticCollector.ts
  src/commands/fix.ts
  src/constants/commands.ts
  src/extension.ts
  src/quickFixProvider.ts
Labels: enhancement

#304 Fix MultipleVariableDeclarationsQuickFix comment handling
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/BaseQuickFix.java
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/coding/MultipleVariableDeclarationsQuickFix.java
Labels: bug

#302 Remove redundant modifiers on interface declarations
  jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/modifier/RedundantModifierQuickFix.java
Labels: bug

#306 fix: Generate temp files according to the folder structure
  src/features/FileSynchronizer.ts
Labels: bug
